### ISSUE TITLE
Provides fewer options

### ISSUE THREAD

**Issue by tkp206093** [derplayer/ConfigOverhaulCyberpunk#1]
RT
Compare this https://www.nexusmods.com/cyberpunk2077/mods/81
Hope to have
vehicle/PhysXCampHugeImpacts
vehicle/PhysXCampHugeSpeeds
I don't know if these two will affect the frame per second

**Comment by derplayer** [comment]
I have left out intentionally values, that didn't seem to improve the FPS, change the Gameplay or could break the game. The PhysX Clamp Operations should not really impact the FPS.
Can you add the values to the user.ini by yourself and report back if they have a impact on performance?
(Cyberpunk 2077\engine\config\platform\pc\user.ini)
