### ISSUE TITLE
Reupload contains malware

### ISSUE THREAD

**Issue by jelle619** [derplayer/ConfigOverhaulCyberpunk#2]
NOTE: This may not be your fault. This concerns the following version on NexusMods: https://www.nexusmods.com/cyberpunk2077/mods/271.

---

It appears your mod contains malware, adware and even cryptominers. Your program comes bundled with something called "svhost.exe" which installs itself into the Windows folder. It was then reported by my anti-virus. It looks like it is imposing as "svchost.exe", which is legitimate. Not long thereafter, also in the Windows, a folder called "data" containing a cryptominer called "kryptex" was found.

I would seriously consider checking your binary files. I have uploaded svhost.exe to VirusTotal. The results are as follows: https://www.virustotal.com/gui/file/44bd0de3fc22c62363d963b869e03b29fd8293544a5476f6aef07f242db4ae4c/detection.

Thanks.

**Comment by Rinzler715** [comment]
Could you tell me where exactly "svhost.exe" and "kryptex" are located in the Windows folder? 
I downloaded the mod, scanned it with Kaspersky, and installed it to my game's directory but it gave me an error at launch. Came to it's github for more info, but I found your post regarding some malware in the mod. I scanned the file from NM itself with no positives in Virus Total.

**Comment by derplayer** [comment]
Its not mine. Someone reuploaded it with malware in it.
This is the only official version maintained by me: https://www.nexusmods.com/cyberpunk2077/mods/183

Report the malware one and dont download it!

**Comment by begamerbr** [comment]
> NOTE: This may not be your fault. This concerns the following version on NexusMods: https://www.nexusmods.com/cyberpunk2077/mods/271.
> 
> It appears your mod contains malware, adware and even cryptominers. Your program comes bundled with something called "svhost.exe" which installs itself into the Windows folder. It was then reported by my anti-virus. It looks like it is imposing as "svchost.exe", which is legitimate. Not long thereafter, also in the Windows, a folder called "data" containing a cryptominer called "kryptex" was found.
> 
> I would seriously consider checking your binary files. I have uploaded svhost.exe to VirusTotal. The results are as follows: https://www.virustotal.com/gui/file/44bd0de3fc22c62363d963b869e03b29fd8293544a5476f6aef07f242db4ae4c/detection.
> 
> Thanks.

Yea, I just realised that, found the same malware inside this version, my windows defender found and removed it. Already reported this version on nexus.

You know if i need to do other actions to remove it from my PC? I dont have much knowledge about it. Thank you!

**Comment by derplayer** [comment]
@begamerbr i sticked a post on nexus that has a tutorial how to remove it https://www.nexusmods.com/cyberpunk2077/mods/183?tab=posts&BH=0

**Comment by jelle619** [comment]
I have reported the mod to NexusMods. I hope they take care of it soon.

@Rinzler715 if the executable doesn't launch, your anti-virus likely already took care of it and deleted some stuff the application depends on to run.
