### ISSUE TITLE
Disabling async compute is useless

### ISSUE THREAD

**Issue by Heliumrich** [derplayer/ConfigOverhaulCyberpunk#3]
Ryzen 7 3700X, GTX 1060 6Gb, not even a 1 FPS diff..

Tried in different spot, and of course restarting the game each time, and loading the exact same save.

May be useful for GTX 9XX, but not for +1XXX

It was when running the game at a high preset, so with my gpu at 100% struggling to reach 40fps. So the case where it should help him the most...

**Comment by derplayer** [comment]
Well, for some folks it works for other not. (someone people for example said gtx 1070 with disabled async compute gives extra 5-10 fps)
